# Gradle settings
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

# Mod properties
mod.id=torohealth
mod.name=ToroHealth Damage Indicators
mod.version=1.19-2.0.0
mod.group=net.torocraft
mod.description=Health bars will appear in the top left corner for the entity in the player's crosshairs.\nDisplays damage indicators and health bars for all entities.
