modLoader = "javafml"
loaderVersion = "*"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/bshuler/ToroHealth/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = '''${description}'''
authors = "ToroCraft, Bert Shuler"
displayURL = "https://github.com/bshuler/ToroHealth"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"
